-- saving customers
INSERT INTO T_CUSTOMER (ADDRESS, PASSWORD, LOYALTY_CARD_NUMBER) VALUES('calle las adelfas', '1111', '456-654');
INSERT INTO T_CUSTOMER (ADDRESS, PASSWORD, LOYALTY_CARD_NUMBER) VALUES('calle tulipan', '2222', '789-987');
