version: "3.9"
services:
  mysql:
    image: mysql:8.0.22    
    ports:
    - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=eoloplantsDB    
    volumes:
      - ./mysql:/var/lib/mysql      
    
  rabbitMQ:
    image: rabbitmq:3-management  
    ports:
    - 15672:15672

  mongo:
    image: mongo
    ports:
    - 27017:27017  
    environment:
      - MONGO_INITDB_DATABASE=topo
    volumes:
      - ./mongo:/data/db

  