version: '3.9'
services:
  mysql:
    image: mysql:8.0.25
    ports:
      - 3306:3306
    environment:
      # Enviroment variables for securize MySQL and create default Database
      - MYSQL_DATABASE=customer
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
      - ./mysql_db:/var/lib/mysql
    restart: always

  customer:
    image: juaneb/split_table_customer_v2
    ports:
      - 8080:8080
    environment:
      # Enviroment variables for connect to MySQL
      - MYSQL_HOST=mysql
    depends_on:
      - mysql
    restart: on-failure

  finance:
    image: juaneb/split_table_finance_v2
    ports:
      - 8090:8090
    environment:
      - MYSQL_HOST=mysql
      - HOST=customer
    restart: on-failure