version: '3.9'
services:
  mysql:
    image: mysql:8.0.25
    ports:
      - 3306:3306
    environment:
      # Enviroment variables for securize MySQL and create default Database
      - MYSQL_DATABASE=employee
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
      - ./mysql_db:/var/lib/mysql
    restart: always   

  employee:
    image: juaneb/aggregate_exposing_monolith_employee_v2
    ports:
      - 8080:8080
    environment:
      - MYSQL_HOST=mysql        
    restart: on-failure

  monolith:
    image: juaneb/aggregate_exposing_monolith_monolith_v2
    ports:
      - 8090:8090
    environment:
      # Enviroment variables for connect to MySQL
      - MYSQL_HOST=mysql
      - HOST=employee
    depends_on:
      - mysql
    restart: on-failure

  catalog:
    image: juaneb/aggregate_exposing_monolith_catalog_v2
    ports:
      - 8100:8100
    environment:
      # Enviroment variables for connect to MySQL
      - MYSQL_HOST=mysql
      - HOST=employee
    depends_on:
      - mysql
    restart: on-failure