version: '3.9'
services:
  mysql:
    image: mysql:8.0.25
    ports:
      - 3306:3306
    environment:
      # Enviroment variables for securize MySQL and create default Database
      - MYSQL_DATABASE=order
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
      - ./mysql_db:/var/lib/mysql
    restart: always

  monolith:
    image: juaneb/split_table_monolith_v1
    ports:
      - 8080:8080
    environment:
      # Enviroment variables for connect to MySQL
      - MYSQL_HOST=mysql
    depends_on:
      - mysql
    restart: on-failure

