apiVersion: networking.k8s.io/v1
kind: Ingress  
metadata:  
  name: eoloplanner-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:  
  rules:
   - host: cluster-ip
     http:
      paths:
      - path: /(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: server-service
            port:
              number: 3000
      - path: /toposervice(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: toposervice
            port:
              number: 8080