---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: planner-deploy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: planner
  replicas: 1
  template:
    metadata:
      labels:
        app: planner
    spec:
      securityContext:
          runAsUser: 1000
      restartPolicy: Always
      containers:
      - name: planner
        image: oscarsotosanchez/planner:v1.0
        env:
        - name: TOPO_HOST
          value: toposervice-service
        - name: TOPO_PORT
          value: "8080"
        - name: GRPC_CLIENT_WEATHERSERVER_ADDRESS
          value: static://weatherservice-service:9090
        - name: SPRING_RABBITMQ_HOST
          value: rabbitmq-service
        - name: SPRING_RABBITMQ_PORT
          value: "5672"
        - name: SPRING_RABBITMQ_USERNAME
          value: root
        - name: SPRING_RABBITMQ_PASSWORD
          value: password
        securityContext:
          allowPrivilegeEscalation: false 


---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: planner
spec:
  podSelector:
    matchLabels:
      app: planner
  egress:
  - to:    
    - podSelector:
        matchLabels:
          app: weatherservice
    - podSelector:
        matchLabels:
          app: toposervice
    ports:
    - port: 8080
      protocol: TCP
    - port: 9090
      protocol: TCP
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: weatherservice
      - podSelector:
          matchLabels:
            app: toposervice
      ports:
      - port: 8080
        protocol: TCP
      - port: 9090
        protocol: TCP