---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-planner-deploy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-planner
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-planner
        dns-policy: enabled
    spec:
      securityContext:
        runAsUser: 1001
      restartPolicy: Always
      containers:
      - name: {{ .Release.Name }}-planner
        image: {{ print .Values.planner.deployment.image.repository ":" .Values.planner.deployment.image.tag }}
        env:
        - name: TOPO_HOST
          value: toposervice-service
        - name: TOPO_PORT
          value: "8080"
        - name: GRPC_CLIENT_WEATHERSERVER_ADDRESS
          value: static://weatherservice-service:9090
        - name: SPRING_RABBITMQ_HOST
          value: rabbitmq-service
        - name: SPRING_RABBITMQ_PORT
          value: "5672"
        - name: SPRING_RABBITMQ_USERNAME
          value: root
        - name: SPRING_RABBITMQ_PASSWORD
          value: password
---
{{- if .Values.common.networkPolicyEnabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-planner-to-rabbit-weather-topo
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-planner
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-rabbitmq
    ports:
    - port: 5672
      protocol: TCP
  - to:
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-weatherservice
    ports:
    - port: 9090
      protocol: TCP
  - to:
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-toposervice
    ports:
    - port: 8080
      protocol: TCP
{{- end }}      
