version: '3.9'
services:
  mysql:
    image: mysql:8.0.25
    ports:
      - 3306:3306
    environment:
      # Enviroment variables for securize MySQL and create default Database
      - MYSQL_DATABASE=monolith
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
      - ./mysql_db:/var/lib/mysql
    restart: always
