apiVersion: mongo/v1 
kind: Deployment
metadata:
  name: dbmongo
spec:
  selector:
    matchLabels:
      app: dbmongo
  template:
    metadata:
      labels:
        app: dbmongo
    spec:
      containers:
      - name: mongo
        image: mongo:4.2.12-bionic
        env:
        - name: MONGO_INITDB_DATABASE
          value: topoDB
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: password
---
apiVersion: v1
kind: Service
metadata:
  name: dbmongo
spec:
  ports:
  - port: 27017
  - port: 27018
  - port: 27019
  selector:
    app: dbmongo
  type: ClusterIP