apiVersion: apps/v1
kind: Deployment
metadata:
  name: planner
spec:
  selector:
    matchLabels:
      app: planner
  replicas: 1
  template:
    metadata:
      labels:
        app: planner
    spec:
      containers:
      - name: planner
        image: oscarsotosanchez/planner:v1.0
        env:
        - name: TOPO_HOST
          value: toposervice
        - name: TOPO_PORT
          value: '8080'
        - name: GRPC_CLIENT_WEATHERSERVER_ADDRESS
          value: static://weatherservice:9090
        - name: SPRING_RABBITMQ_HOST
          value: rabbitmq
        - name: SPRING_RABBITMQ_PORT
          value: '5672'
        - name: SPRING_RABBITMQ_USERNAME
          value: root
        - name: SPRING_RABBITMQ_PASSWORD
          value: password
---
apiVersion: v1
kind: Service
metadata:
  name: planner
  labels:
    app: planner
spec:
  ports:
  - port: 8080
  selector:
    app: planner
  type: ClusterIP