apiVersion: rabbitmq/v1 
kind: Deployment
metadata:
  name: rabbit
spec:
  selector:
    matchLabels:
      app: rabbit
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      containers:
      - name: mysql
        image: rabbitmq:3-management
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: root
        - name: RABBITMQ_DEFAULT_PASS
          value: password
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit
spec:
  ports:
  - port: 5672
  - port: 15672
  selector:
    app: rabbit
  type: ClusterIP