apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: oscarsotosanchez/server:v1.0
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_DB
          value: eoloplantsDB
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASS
          value: password
        - name: RABBITMQ_URL
          value: amqp://root:password@rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: serverservice
  labels:
    app: server
spec:
  ports:
  - port: 3000
  selector:
    app: server
  type: NodePort