apiVersion: apps/v1
kind: Deployment
metadata:
  name: toposervice
spec:
  selector:
    matchLabels:
      app: toposervice
  replicas: 1
  template:
    metadata:
      labels:
        app: toposervice
    spec:
      containers:
      - name: java
        image: juaneb/jescribanobdreygtoposervice
        env:
        - name: spring.data.mongodb.host
          value: mongo
        - name: spring.data.mongodb.port
          value: '27017'
        - name: spring.data.mongodb.database
          value: topo
---
apiVersion: v1
kind: Service
metadata:
  name: toposervice
  labels:
    app: toposervice
spec:
  ports:
  - port: 8080
  selector:
    app: toposervice
  type: ClusterIP
