AWSTemplateFormatVersion: 2010-09-09
Description: EC2

Parameters:
  AMIId:
    Description: The ami to use (it must be an AMI on the current region and must be Ubuntu 20.04)
    Type: 'AWS::EC2::Image::Id'
    Default: 'ami-013f17f36f8b1fefb'
  DBPassword:
    Description: Database password
    Type: String
    NoEcho: true
    MinLength: 8
  BuckectPrac2:
    Description: The name of the Bucket
    Type: String
  UrlDownloadApp:
    Description: Url app
    Type: String
    Default: 'https://s3.amazonaws.com/practica-2.cloud.michel/app.jar'

Resources:

  myRoleBucket:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"

  myRoleBucketInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref myRoleBucket

  myRoleBucketPolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: myRoleBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: "*"
            Resource: "*"
      Roles:
        - !Ref myRoleBucketInstanceProfile


  prac2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: spring-8443
      GroupDescription: "SG for Prac2 ports 443"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '8443'
          ToPort: '8443'
          CidrIp: 0.0.0.0/0
  rdsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "SG for MySQL RDS"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '3306'
          ToPort: '3306'
          SourceSecurityGroupName: !Ref prac2SecurityGroup # Sólo permite acceso a las instancias de este grupo
  rdsDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t2.micro
      AllocatedStorage: 10
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      DBInstanceIdentifier: db-prac2-id
      DBName: dbprac2aws
      Engine: mysql
      EngineVersion: 8.0
      MasterUsername: admin
      MasterUserPassword: !Ref DBPassword
      MultiAZ: false
      PubliclyAccessible: true
      StorageEncrypted: false
      VPCSecurityGroups:
        - !GetAtt rdsSecurityGroup.GroupId
      Tags:
        - Key: Name
          Value: mca-cf-rds-prac2
  myEC2Instance:
    Type: AWS::EC2::Instance
    DependsOn: rdsDBInstance
    Properties:
      KeyName: "dreyg-jescribanob-aws-virginia"
      ImageId: !Ref AMIId
      InstanceType: "t2.micro"
      Monitoring: true
      SecurityGroups:
        - !Ref prac2SecurityGroup
      IamInstanceProfile:
        - !Ref myRoleBucketInstanceProfile
      UserData:
        Fn::Base64:
          Fn::Sub:
            - |
              #!/bin/bash -ex
              apt update && apt install -y openjdk-11-jre-headless
              wget ${Url}
              sudo java -jar -Dspring.profiles.active=production app.jar --server.port=443 --spring.datasource.url=${JDBC} --spring.datasource.username=admin --spring.datasource.password=${Pass} --amazon.s3.bucket-name=${BucketName} --amazon.s3.endpoint=${BucketURL} --amazon.s3.region=us-east-1
            - Url: !Ref UrlDownloadApp
              JDBC: !Join [ '', [ 'jdbc:mysql://', !GetAtt [ rdsDBInstance, Endpoint.Address ], /, dbprac2aws ] ]
              Pass: !Ref DBPassword
              BucketName: !Ref BuckectPrac2
              BucketURL: !GetAtt [ myBucket, WebsiteURL ]
      Tags:
        - Key: Name
          Value: jescribanob-dreyg-01
  myBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BuckectPrac2
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

Outputs:
  WebSiteURL:
    Value:
      !Join
      - ''
      - - "https://"
        - !GetAtt myEC2Instance.PublicDnsName
    Description: "Application Endpoint"
